### ISSUE TITLE
Machine Ideas

### ISSUE THREAD

**Issue by UniversalRed** [UniversalRed/RedstoneDistortion#7]
Currently within RD, there have been 3 machines created:
- Mechanical Furnace
- Mechanical Transfuser
- Mechanical Desolator

These three machines are the basic "easy to use machines", but maybe if you suggest, there could be more machines! Moe machines = more fun :)

So, list all your ideas here if you want and make it descriptive enough for me to understand what you mean ;)

**Comment by AEnterprise** [comment]
???

**Comment by UniversalRed** [comment]
I've got a better idea then doing this, I may as well have people make their own issues regarding the new machines and use this as a template. It might look a bit messed up,  but trust me, I think I got this.
