### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Cronosus** [UniversalRed/RedstoneDistortion#8]
http://pastebin.com/RKKU7crZ

**Comment by UniversalRed** [comment]
@Cronosus , you will need the latest version of forge for 1.7.10, LL does not work with this mod, you can get the forge version here: http://files.minecraftforge.net/

**Comment by Cronosus** [comment]
i use last version of forge

**Comment by UniversalRed** [comment]
The crash that you reported to me came directly from liteloader, I can tell from the com.mumfrey.liteloader.*; from the crash log, if you are using both loaders, than I recommend you not to do that and just stick to forge, because that crash came directly from LL.
